name: Update Year

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (try 1)
        id: checkout1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        continue-on-error: true

      - name: Retry checkout (try 2)
        if: steps.checkout1.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update year in README
        run: |
          YEAR=$(date +'%Y')
          sed -i "s/YEAR/$YEAR/g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add README.md

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "🔄 Atualiza ano automaticamente"
          git push
